=== MiguelALozano/LMactividad2/biblioteca.dtd
<!ELEMENT biblioteca (libros, revistas, periodicos)>
<!ELEMENT libros (libro*)>
<!ELEMENT libro (titulo, indice, capitulos, sinopsis)>
<!ATTLIST libro id ID #REQUIRED 
                tipo_clase (novela|infantil|didactico) #REQUIRED 
                numero_paginas CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)> <!-- Etiqueta común para libros y revistas -->
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (contenido_libro)>
<!ATTLIST capitulo numero_paginas CDATA #REQUIRED>
<!ELEMENT contenido_libro EMPTY>
<!ATTLIST contenido_libro enlace CDATA #REQUIRED>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT revistas (revista*)>
<!ELEMENT revista (titulo, numero_revista, indice, secciones)>
<!ATTLIST revista id ID #REQUIRED
                  tipo_clase (informatica|corazon|investigacion|coches|otros)
                  numero_paginas CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT secciones (seccion_revista+|seccion_periodico+)>
<!ELEMENT seccion_revista (contenido)>
<!ATTLIST seccion_revista numero_paginas CDATA #REQUIRED>
<!ELEMENT contenido_revista EMPTY>
<!ATTLIST contenido_revista enlace CDATA #REQUIRED>

<!ELEMENT periodicos (periodico*)>
<!ELEMENT periodico (secciones)>
<!ATTLIST periodico id ID #REQUIRED 
                    tipo_clase (nacional|internacional) #REQUIRED 
                    fecha_publicacion CDATA #REQUIRED>
<!ATTLIST seccion_periodico tipo_seccion (economica|opinion|deportes|nacional|internacional) #REQUIRED>
<!ELEMENT seccion_periodico (articulos+)>
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (contenido_articulo)>
<!ELEMENT contenido_articulo (#PCDATA)>
<!ATTLIST articulo autor CDATA #REQUIRED>




<!-- En el elemento raíz "biblioteca" consideramos la opción de
añadir un interrogante al final de la sentencia, para que las secciones
pudiesen estar o no presentes. -->

=== MiguelALozano/LMactividad2/bibliotecaConDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca>
    
    <libros>
        <libro id="L0001" tipo_clase="novela" numero_paginas="205">
            <titulo>Patata</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="20">
                    <contenido_libro enlace="https://www.patata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>Una Patata muy maja.</sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="infantil" numero_paginas="350">
            <titulo>Patatín</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="10">
                    <contenido_libro enlace="https://www.patatin.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La hija de Patata.</sinopsis>
        </libro>

        <libro id="L0003" tipo_clase="didactico" numero_paginas="700">
            <titulo>Enciclopedia de la Patata.</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="30">
                     <contenido_libro enlace="https://www.wikipatata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La enciclopedia preferida de estas dos.</sinopsis>
        </libro>
    </libros>
    
    <revistas>
        <revista id="R0001" tipo_clase="informatica" numero_paginas="50">
            <titulo>Disco Duro</titulo>
            <numero_revista>107</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="12">
                    <contenido_revista enlace="https://www.discoduro.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="corazon" numero_paginas="47">
            <titulo>Marujeos</titulo>
            <numero_revista>21</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="4">
                    <contenido_revista enlace="https://www.marujeos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0003" tipo_clase="investigacion" numero_paginas="105">
            <titulo>Todo ciencia</titulo>
            <numero_revista>56</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="34">
                    <contenido_revista enlace="https://www.todociencia.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0004" tipo_clase="coches" numero_paginas="87">
            <titulo>Súper coches</titulo>
            <numero_revista>98</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="21">
                    <contenido_revista enlace="https://www.supercoches.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0005" tipo_clase="otros" numero_paginas="90">
            <titulo>Coches y motos</titulo>
            <numero_revista>12</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="7">
                    <contenido_revista enlace="https://www.cochesmotos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>

    </revistas>


    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="21/07/2020">
            <secciones>
                <seccion_periodico tipo_seccion="economica">
                    <articulos>
                        <articulo autor="Pepe">
                            <contenido_articulo>A</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="opinion">
                    <articulos>
                        <articulo autor="María">
                            <contenido_articulo>B</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="deportes">
                    <articulos>
                        <articulo autor="Paquito">
                            <contenido_articulo>C</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="nacional">
                    <articulos>
                        <articulo autor="Julia">
                            <contenido_articulo>D</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="internacional">
                    <articulos>
                        <articulo autor="Sara">
                            <contenido_articulo>E</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>

        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="04/03/2020">
            <secciones>
                <seccion_periodico tipo_seccion="economica">
                    <articulos>
                        <articulo autor="Adolfo">
                            <contenido_articulo>A</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="opinion">
                    <articulos>
                        <articulo autor="Elena">
                            <contenido_articulo>B</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="deportes">
                    <articulos>
                        <articulo autor="Felipe">
                            <contenido_articulo>C</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="nacional">
                    <articulos>
                        <articulo autor="Arturo">
                            <contenido_articulo>D</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion="internacional">
                    <articulos>
                        <articulo autor="Clara">
                            <contenido_articulo>E</contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>
    </periodicos>

</biblioteca>

<!-- ==================== REVISTA ====================
 
1. Las revistas a su vez son clasificadas en: informática,
corazón, coches, investigación y otras.

5. De igual forma que en los anteriores, la última etiqueta del
árbol debe ser el contenido con un atributo que referencia al
contenido.
-->


<!-- ==================== PERIÓDICO ====================

Dentro de los periódicos tenemos secciones y un índice.

Cada sección debe contener un atributo identificativo del
tipo de sección, que puede ser:
económica, opinión, deportes, nacional o internacional.

Finalmente, el contenido será el último elemento del árbol,
que necesita un atributo que referencie a la información.

-->
