<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libros, revistas, periodicos)>
    <!-- Tipos de documentos almacenados en la biblioteca -->


    <!-- ZONA LIBROS -->
    <!ELEMENT libros (libro*)>
    <!-- Decidimos que de este elemento podemos tener entre 0 y muchos -->
    <!ELEMENT libro (titulo, indice, capitulos, sinopsis)>
    <!-- Elementos hijos de libro -->
    <!ATTLIST libro
        id ID #REQUIRED
        tipo_clase (novela|infantil|didactico) "novela"
        numero_paginas CDATA #REQUIRED
    >
    <!-- atributos de libro, id de la c-->
    <!ELEMENT capitulos (capitulo+)>
    <!-- capítulos contiene al menos 1 capitulo -->
    <!ELEMENT capitulo (contenido_libro)>
    <!-- A su vez capitulo tiene un elemento hijo que es el contenido del capitulo-->
    <!ATTLIST capitulo numero_paginas CDATA #REQUIRED>
    <!-- Atributo para capitulo, que recoge el número de páginas del mismo-->
    <!-- El elemento contenido_libro se declara como vacio, ya que no tiene ningún texto ni elemento en su interior.
     A dicho contenido se accede a través del atributo enlace -->
    <!ELEMENT contenido_libro EMPTY>
    <!ATTLIST contenido_libro enlace CDATA #REQUIRED>
    <!ELEMENT sinopsis (#PCDATA)>
    <!-- El elemento sipnosis es de tipo texto y recoge un resumen del libro -->


    <!-- ZONA REVISTAS -->
    <!ELEMENT revistas (revista*)>
    <!-- revistas tiene un elemento revista con una cardinalidad de 0 a n -->
    <!-- El elemento revista tiene los elementos hijos: titulo, numero_revista, indice y secciones. 
     A su vez se declaran los atributos de revista que identifican su ID, el tipo de clase y el número de páginas de cada revista-->
    <!ELEMENT revista (titulo, numero_revista, indice, secciones)>
    <!ATTLIST revista
        id ID #REQUIRED
        tipo_clase (informatica|corazon|investigacion|coches|otros) "otros"
        numero_paginas CDATA #REQUIRED
    >
    <!ELEMENT numero_revista (#PCDATA)>
    <!-- Elemento que recoge el número de edición de la revista, se trata como #PCDATA -->
    <!-- El elemento secciones incluye los elementos hijos: seccion revista o seccion periodico, ya que es común a ambas etiquetas y dentro de secciones podrá haber al menos una de cada en su correspondiente seccion -->
    <!ELEMENT secciones (seccion_revista+|seccion_periodico+)>
    <!-- seccion revista, contiene como elemento hijo contenido_revista, que es un elemento vacio donde el contenido es accesible a través del enlace que se declara como atributo. A su vez, sección revista tiene el atributo numero_paginas que recoge el número de paginas de cada seccion. -->
    <!ELEMENT seccion_revista (contenido_revista)>
    <!ATTLIST seccion_revista numero_paginas CDATA #REQUIRED>
    <!ELEMENT contenido_revista EMPTY>
    <!ATTLIST contenido_revista enlace CDATA #REQUIRED>

    
    <!-- ZONA PERIÓDICOS -->
    <!ELEMENT periodicos (periodico*)>
    <!-- Periodicos contiene periodico con una cardinalidad de 0 a n -->
    <!-- El elemento periodico contiene los elementos hijos: indice y secciones. A su vez se le declaran los atributos ID, tipo_clase y fecha_publicacion-->
    <!ELEMENT periodico (indice,secciones)>
    <!ATTLIST periodico
        id ID #REQUIRED
        tipo_clase (nacional|internacional) "nacional"
        fecha_publicacion CDATA #REQUIRED
    >
    <!-- El elemento seccion periodico incluye el elemento articulos que a su vez contendrá el articulo en cardinalidad 1 a n. seccion_periodico contendrá el atributo tipo_seccion_periodico en el que se requiere el tipo de seccion de forma obligatoria. -->
    <!ATTLIST seccion_periodico tipo_seccion_periodico (economica|opinion|deportes|nacional|internacional) #REQUIRED>
    <!ELEMENT seccion_periodico (articulos)>
    <!ELEMENT articulos (articulo+)>
    
    <!-- El elemento articulo contiene el elemento contenido_articulo que es un elemento contenido_articulo vacio, ya que el contenido se ofrece a través del atributo enlace.
    A su vez articulo tiene el atributo autor, que es de tipo texto y  obligatorio.-->
    <!ELEMENT articulo (contenido_articulo)>
    <!ATTLIST articulo autor CDATA #REQUIRED>
    <!ELEMENT contenido_articulo EMPTY>
    <!ATTLIST contenido_articulo enlace CDATA #REQUIRED>


    <!-- ZONA COMÚN -->
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT indice (#PCDATA)>
]>
<!-- elemento raiz -->
<biblioteca>
    <!-- Dentro del elemento raíz, se crean las ramas libros, revistas y periodicos que seran las contenedoras de cada libro, revista y periodico que posea la biblioteca, siguiendo las expecificaciones que dicta el DTD para que además de bien formado, sea válido el documento -->
    <!-- ZONA LIBROS Recoge todos los libros que contiene la biblioteca -->
    <libros>
        <libro id="L0001" numero_paginas="205">
            <titulo>Patata</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="20">
                    <contenido_libro enlace="https://www.patata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>Una Patata muy maja.</sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="infantil" numero_paginas="350">
            <titulo>Patatín</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="10">
                    <contenido_libro enlace="https://www.patatin.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La hija de Patata.</sinopsis>
        </libro>

        <libro id="L0003" tipo_clase="didactico" numero_paginas="700">
            <titulo>Enciclopedia de la Patata.</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="30">
                    <contenido_libro enlace="https://www.wikipatata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La enciclopedia preferida de estas dos.</sinopsis>
        </libro>
    </libros>


    <!-- ZONA REVISTAS contiene todas las revistas de la biblioteca -->
    <revistas>
        <revista id="R0001" tipo_clase="informatica" numero_paginas="50">
            <titulo>Disco Duro</titulo>
            <numero_revista>107</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="12">
                    <contenido_revista enlace="https://www.discoduro.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="corazon" numero_paginas="47">
            <titulo>Marujeos</titulo>
            <numero_revista>21</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="4">
                    <contenido_revista enlace="https://www.marujeos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0003" tipo_clase="investigacion" numero_paginas="105">
            <titulo>Todo ciencia</titulo>
            <numero_revista>56</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="34">
                    <contenido_revista enlace="https://www.todociencia.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0004" tipo_clase="coches" numero_paginas="87">
            <titulo>Súper coches</titulo>
            <numero_revista>98</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="21">
                    <contenido_revista enlace="https://www.supercoches.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0005" numero_paginas="90">
            <titulo>Coches y motos</titulo>
            <numero_revista>12</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="7">
                    <contenido_revista enlace="https://www.cochesmotos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
    </revistas>


    <!-- ZONA PERIÓDICOS Contiene todos los periodicos de la biblioteca -->
    <periodicos>
        <periodico id="P0001" fecha_publicacion="2020-07-21">
            <indice>Índice</indice>
            <secciones>
                <seccion_periodico tipo_seccion_periodico="economica">
                    <articulos>
                        <articulo autor="Pepe">
                            <contenido_articulo enlace="https://www.a.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="opinion">
                    <articulos>
                        <articulo autor="María">
                            <contenido_articulo enlace="https://www.b.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="deportes">
                    <articulos>
                        <articulo autor="Paquito">
                            <contenido_articulo enlace="https://www.c.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="nacional">
                    <articulos>
                        <articulo autor="Julia">
                            <contenido_articulo enlace="https://www.d.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="internacional">
                    <articulos>
                        <articulo autor="Sara">
                            <contenido_articulo enlace="https://www.e.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>

        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="2020-03-04">
            <indice>Índice</indice>
            <secciones>
                <seccion_periodico tipo_seccion_periodico="economica">
                    <articulos>
                        <articulo autor="Adolfo">
                            <contenido_articulo enlace="https://www.a.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="opinion">
                    <articulos>
                        <articulo autor="Elena">
                            <contenido_articulo enlace="https://www.b.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="deportes">
                    <articulos>
                        <articulo autor="Felipe">
                            <contenido_articulo enlace="https://www.c.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="nacional">
                    <articulos>
                        <articulo autor="Arturo">
                            <contenido_articulo enlace="https://www.d.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="internacional">
                    <articulos>
                        <articulo autor="Clara">
                            <contenido_articulo enlace="https://www.e.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>
    </periodicos>
</biblioteca>