=== MiguelALozano/LMactividad2/biblioteca.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <annotation>
        <documentation>
            Esquema que marca la estructura de la biblioteca de Territorio_Web
         </documentation>
    </annotation>
    <!-- El nodo raiz se llama biblioteca-->
    <element name="biblioteca">
        <complexType>
            <sequence>
                <!-- Sobra el minOccurs? -->
                <!-- ZONA LIBROS -->
                <element name="libros" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="libro" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                    <sequence>
                                        <element name="titulo" type="string" />
                                        <element name="indice" type="string" />
                                        <element name="capitulos">
                                            <complexType>
                                                <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                                <sequence>
                                                    <element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <!-- PONER QUE EL ELEMENTO VA VACÍO -->
                                                                <element name="contenido_libro">
                                                                    <!-- OJO: NECESITAMOS COMPLEXTYPE PARA METER UN ATRIBUTO -->
                                                                    <complexType>
                                                                        <attribute name="enlace" type="anyURI" use="required"></attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="numero_paginas" use="required">
                                                                <simpleType>
                                                                    <restriction base="integer">
                                                                        <minInclusive value="1"></minInclusive>
                                                                        <maxInclusive value="99999"></maxInclusive>
                                                                    </restriction>
                                                                </simpleType>
                                                            </attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="sinopsis" type="string" />
                                    </sequence>
                                    <!-- FALTA EXPRESIÓN REGULAR -->
                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[L]{1}[0-9]{4}"></pattern>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="novela"></enumeration>
                                                <enumeration value="infantil"></enumeration>
                                                <enumeration value="didactico"></enumeration>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="numero_paginas" use="required">
                                        <simpleType>
                                            <restriction base="integer">
                                                <minInclusive value="1"></minInclusive>
                                                <maxInclusive value="99999"></maxInclusive>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

                <!-- ZONA REVISTAS -->
                <element name="revistas" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="revista" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                    <sequence>
                                        <element name="titulo" type="string" />
                                        <element name="numero_revista">
                                            <simpleType>
                                                <restriction base="integer">
                                                    <minInclusive value="1"></minInclusive>
                                                    <maxInclusive value="99999"></maxInclusive>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="indice" type="string" />
                                        <element name="secciones">
                                            <complexType>
                                                <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                                <sequence>
                                                    <element name="seccion_revista" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="contenido_revista">
                                                                    <!-- OJO: NECESITAMOS COMPLEXTYPE PARA METER UN ATRIBUTO -->
                                                                    <complexType>
                                                                        <attribute name="enlace" type="anyURI" use="required"></attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="numero_paginas" use="required">
                                                                <simpleType>
                                                                    <restriction base="integer">
                                                                        <minInclusive value="1"></minInclusive>
                                                                        <maxInclusive value="99999"></maxInclusive>
                                                                    </restriction>
                                                                </simpleType>
                                                            </attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[R]{1}[0-9]{4}"></pattern>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="informatica"></enumeration>
                                                <enumeration value="corazon"></enumeration>
                                                <enumeration value="investigacion"></enumeration>
                                                <enumeration value="coches"></enumeration>
                                                <enumeration value="otros"></enumeration>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="numero_paginas" use="required">
                                        <simpleType>
                                            <restriction base="integer">
                                                <minInclusive value="1"></minInclusive>
                                                <maxInclusive value="99999"></maxInclusive>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

                <!-- ZONA PERIÓDICOS -->
                <element name="periodicos" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="periodico" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                    <sequence>
                                        <element name="indice" type="string" />
                                        <element name="secciones">
                                            <complexType>
                                                <!-- Al poner sequence, no hace falta poner required en los elementos de dentro-->
                                                <sequence>
                                                    <element name="seccion_periodico" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="articulos">
                                                                    <complexType>
                                                                        <sequence>
                                                                            <element name="articulo" minOccurs="1">
                                                                                <complexType>
                                                                                    <sequence>
                                                                                        <element name="contenido_articulo">
                                                                                            <!-- OJO: NECESITAMOS COMPLEXTYPE PARA METER UN ATRIBUTO -->
                                                                                            <complexType>
                                                                                                <attribute name="enlace" type="anyURI" use="required"></attribute>
                                                                                            </complexType>
                                                                                        </element>
                                                                                    </sequence>
                                                                                    <attribute name="autor" type="string" use="required"></attribute>
                                                                                </complexType>
                                                                            </element>
                                                                        </sequence>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="tipo_seccion_periodico" use="required">
                                                                <simpleType>
                                                                    <restriction base="string">
                                                                        <enumeration value="economica"></enumeration>
                                                                        <enumeration value="opinion"></enumeration>
                                                                        <enumeration value="deportes"></enumeration>
                                                                        <enumeration value="nacional"></enumeration>
                                                                        <enumeration value="internacional"></enumeration>
                                                                    </restriction>
                                                                </simpleType>
                                                            </attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[P]{1}[0-9]{4}"></pattern>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="nacional"></enumeration>
                                                <enumeration value="internacional"></enumeration>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="fecha_publicacion" type="date" use="required"></attribute>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== MiguelALozano/LMactividad2/bibliotecaXSDexterno.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libros>
        <libro id="L0001" numero_paginas="205">
            <titulo>Patata</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="20">
                    <contenido_libro enlace="https://www.patata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>Una Patata muy maja.</sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="infantil" numero_paginas="350">
            <titulo>Patatín</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="10">
                    <contenido_libro enlace="https://www.patatin.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La hija de Patata.</sinopsis>
        </libro>

        <libro id="L0003" tipo_clase="didactico" numero_paginas="700">
            <titulo>Enciclopedia de la Patata.</titulo>
            <indice>Índice</indice>
            <capitulos>
                <capitulo numero_paginas="30">
                    <contenido_libro enlace="https://www.wikipatata.com"></contenido_libro>
                </capitulo>
            </capitulos>
            <sinopsis>La enciclopedia preferida de estas dos.</sinopsis>
        </libro>
    </libros>

    <!-- ZONA REVISTAS -->
    <revistas>
        <revista id="R0001" tipo_clase="informatica" numero_paginas="50">
            <titulo>Disco Duro</titulo>
            <numero_revista>107</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="12">
                    <contenido_revista enlace="https://www.discoduro.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="corazon" numero_paginas="47">
            <titulo>Marujeos</titulo>
            <numero_revista>21</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="4">
                    <contenido_revista enlace="https://www.marujeos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0003" tipo_clase="investigacion" numero_paginas="105">
            <titulo>Todo ciencia</titulo>
            <numero_revista>56</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="34">
                    <contenido_revista enlace="https://www.todociencia.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0004" tipo_clase="coches" numero_paginas="87">
            <titulo>Súper coches</titulo>
            <numero_revista>98</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="21">
                    <contenido_revista enlace="https://www.supercoches.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
        <revista id="R0005" numero_paginas="90">
            <titulo>Coches y motos</titulo>
            <numero_revista>12</numero_revista>
            <indice>Índice</indice>
            <secciones>
                <seccion_revista numero_paginas="7">
                    <contenido_revista enlace="https://www.cochesmotos.com"></contenido_revista>
                </seccion_revista>
            </secciones>
        </revista>
    </revistas>

    <!-- ZONA PERIÓDICOS -->
    <periodicos>
        <periodico id="P0001" fecha_publicacion="2020-07-21">
            <indice>Índice</indice>
            <secciones>
                <seccion_periodico tipo_seccion_periodico="economica">
                    <articulos>
                        <articulo autor="Pepe">
                            <contenido_articulo enlace="https://www.a.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="opinion">
                    <articulos>
                        <articulo autor="María">
                            <contenido_articulo enlace="https://www.b.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="deportes">
                    <articulos>
                        <articulo autor="Paquito">
                            <contenido_articulo enlace="https://www.c.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="nacional">
                    <articulos>
                        <articulo autor="Julia">
                            <contenido_articulo enlace="https://www.d.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="internacional">
                    <articulos>
                        <articulo autor="Sara">
                            <contenido_articulo enlace="https://www.e.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>

        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="2020-03-04">
            <indice>Índice</indice>
            <secciones>
                <seccion_periodico tipo_seccion_periodico="economica">
                    <articulos>
                        <articulo autor="Adolfo">
                            <contenido_articulo enlace="https://www.a.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="opinion">
                    <articulos>
                        <articulo autor="Elena">
                            <contenido_articulo enlace="https://www.b.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="deportes">
                    <articulos>
                        <articulo autor="Felipe">
                            <contenido_articulo enlace="https://www.c.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="nacional">
                    <articulos>
                        <articulo autor="Arturo">
                            <contenido_articulo enlace="https://www.d.com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
                <seccion_periodico tipo_seccion_periodico="internacional">
                    <articulos>
                        <articulo autor="Clara">
                            <contenido_articulo enlace="https://www..com"></contenido_articulo>
                        </articulo>
                    </articulos>
                </seccion_periodico>
            </secciones>
        </periodico>
    </periodicos>
</biblioteca>
